### ISSUE TITLE
Picasso: App Store Screenshot Tool

### ISSUE THREAD

**Issue by mpdifran** [jamesjingyi/free-mac-apps#1]
Hi! 

I'd like to submit my app, Picasso to this list! It's free to download and use, but does have IAP for premium features. The IAP don't block the main workflow though, they're only adding onto the core experience.

https://picassoapp.ca

**Comment by jamesjingyi** [comment]
I am downloading today and will have a play, thanks for your submission!

**Comment by jamesjingyi** [comment]
I have added, thanks!
