### ISSUE TITLE
Incorrect spreadsheet link for Grand Perspective

### ISSUE THREAD

**Issue by z-wilson** [jamesjingyi/free-mac-apps#12]
The last entry on your spreadsheet in the first section (Essentials) appears to point to Aerial Screensaver rather than Grand Perspective:

![image](https://github.com/user-attachments/assets/e7cf98d6-3721-427f-afde-26d6ebc1cf75)

**Comment by jamesjingyi** [comment]
Oooh amazing thank you! 🙌 I have fixed that! Not sure what was happening there — it was both the wrong link, and also linking to the wrong place
