### ISSUE TITLE
Maccy - Lightweight Clipboard manager for Mac

### ISSUE THREAD

**Issue by deshabhishek007** [jamesjingyi/free-mac-apps#2]
Maccy is a lightweight clipboard manager for macOS. It keeps the history of what you copy and lets you quickly navigate, search and use previous clipboard content.

https://github.com/p0deje/Maccy/

**Comment by jamesjingyi** [comment]
Hiya this looks great! I used to use Copyclip for this, but then switched to using a Raycast function, but this would be great to add if people aren't installing Raycast. I shall install and get back to you!

**Comment by jamesjingyi** [comment]
I like! I have added it in, thanks for the recommendation!

**Comment by youtextme** [comment]
Maccy is great when you want a clipboard-only tool. If the reader already uses (or will use) a launcher, free Raycast clipboard history covers the common case — text + images — without a second hotkey.

Reach for Maccy when you need deeper history UX / pinning rituals the launcher does not match.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
