### ISSUE TITLE
New Music App - AutoSpoto

### ISSUE THREAD

**Issue by mariemac5** [jamesjingyi/free-mac-apps#5]
AutoSpoto creates Spotify playlists out of your iMessage chats. Available for free on Mac App Store. https://apple.co/49Lnlgb

**Comment by jamesjingyi** [comment]
Looking at this now, but might take a little bit since I don't use Spotify!

**Comment by mariemac5** [comment]
okay, no worries! Thanks so much. If you have an account, you could see if anyone else has ever sent you a chat as well. Appreciate it!

Marie
________________________________

**Comment by jamesjingyi** [comment]
Hey sorry I never replied to this! I added it in — I don't use Spotify myself, so had to get some friends to check it out. Thanks again for the recommendation :)
