### ISSUE TITLE
Warp terminal

### ISSUE THREAD

**Issue by vincenzolegrottaglie** [jamesjingyi/free-mac-apps#6]
Warp is a modern, Rust-based terminal with AI built in

**Comment by jamesjingyi** [comment]
Oooh this looks good! Installing now!

**Comment by vincenzolegrottaglie** [comment]
Let me know if you like it!

**Comment by jamesjingyi** [comment]
I tested this for a while and really liked it! I will add this today, thanks for the suggestion!
