### ISSUE TITLE
Sindre Sorhus Apps

### ISSUE THREAD

**Issue by SKaplanOfficial** [jamesjingyi/free-mac-apps#8]
[Sindre Sorhus](https://sindresorhus.com/apps) has a bunch of apps that are free, high-quality, and very useful. Many of them are open-source as well.

Some I personally use and recommend are [Pasteboard Viewer](https://sindresorhus.com/pasteboard-viewer) (lets you view the contents of the clipboard in multiple formats), [Actions](https://sindresorhus.com/actions) (adds *many* new Shortcuts), and [Folder Peek](https://sindresorhus.com/folder-peek) (provides quick-access to folders & files via a menubar app). All of these are available on the Mac App Store.

I'm not affiliated in any way; I just really appreciate this developer's work.

**Comment by jamesjingyi** [comment]
Amazing thank you, these are great! I have added all 3 to the sheet, and added a few more that I also thought might be useful including:

- [Second Clock](https://sindresorhus.com/second-clock)
- [Command X](https://sindresorhus.com/command-x)
- [Spaced](https://sindresorhus.com/spaced)
- [Plain Text Editor](https://sindresorhus.com/plain-text-editor)
- [Gifski](https://sindresorhus.com/gifski)

I was already using [Velja](https://sindresorhus.com/velja) from that dev, and definitely appreciate their work! Thanks again for your suggestion :)
